### ISSUE TITLE
climate explorer backend gets file not found error when tryng to open files

### ISSUE THREAD

**Issue by corviday** [pacificclimate/docker-geospatial-python#12]
~~For unknown reasons, rasterio version 1.2.6 sometimes has trouble opening files, such as the new change factor files. Rasterio 1.2.1 does not have these issues. Upgrading to rasterio1.2.6. was a byproduct of trying to fix a build issue, so it should be possible to undo it.~~

**Comment by corviday** [comment]
I spent a lot time poring over the climate explorer backend code and Pipfiles, assuming that a package update under the hood had broken rasterio, but ultimately the clue to solving this issue came from logging into a running docker container and trying to use gdalinfo on a file, which yielded the following error message, followed by a core dump:

```
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.12.0, library is 1.12.1
```
I first tried setting the suggested environment variable, `HDF5_DISABLE_VERSION_CHECK` to 1 in the container while it was running. This resulted in gdalinfo running correctly, but the actual backend still was unable to open the files in question.

After a bunch of other things that didn't pan out, I decided to investigate the `osgeo/gdal` docker, since that is where the HDF5 library is installed.  When I went to run it, docker informed me there was a new version of `osgeo/gdal`. I logged into the new version of `osgeo/gdal` and ran `gdalinfo` on the files, and did not get the error message, so it seemed that osgeo had resolved the header issue themselves. 

I went to rebuild `pcic/geospatial` so that it would use the new image from osgeo, but received the following error message:

```
  Downloading netCDF4-1.6.0.tar.gz (774 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 774.2/774.2 kB 30.3 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Package hdf5 was not found in the pkg-config search path.
      Perhaps you should add the directory containing `hdf5.pc'
      to the PKG_CONFIG_PATH environment variable
      Package 'hdf5', required by 'virtual:world', not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-h6ttowkb/netcdf4_ea643b22576443fe86a379e5d5bd52e4/setup.py", line 559, in <module>
          check_api(inc_dirs,netcdf_lib_version)
        File "/tmp/pip-install-h6ttowkb/netcdf4_ea643b22576443fe86a379e5d5bd52e4/setup.py", line 130, in check_api
          has_szip_support = bool(int(line.split()[2]))
      ValueError: invalid literal for int() with base 10: '/*!<'
      reading from setup.cfg...
      using nc-config...
      checking /usr/include ...
      HDF5 library version: 1.10.6 headers found in /usr/include
      using netcdf library version b'4.7.4'
      using Cython to compile netCDF4.pyx...
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

After fooling around trying to figure out the right value for the `PKG_CONFIG_PATH` environment variable, I realized that netCDF4 version 1.5.x did not have the issue, only version 1.6.0. I [pinned netCDF4 to version 1.5.7](https://github.com/pacificclimate/docker-geospatial-python/pull/11/commits/b0581639c0847638b3ace870e04dfb8c5621df4c), which is ultimately the only change that needed to be  made to fix this problem, since osgeo had already repaired the underlying issue.
